# Generated by Django 5.1.3 on 2024-11-13 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Docentes', '0002_alter_docente_table'),
        ('Estudiantes', '0002_alter_estudiante_table'),
        ('Grupos', '0002_alter_grupo_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiantes_en_Grupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Docentes.docente')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estudiantes.estudiante')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grupos.grupo')),
            ],
            options={
                'db_table': 'Estudiantes_en_Grupos',
                'unique_together': {('estudiante', 'grupo', 'docente')},
            },
        ),
    ]
