# Generated by Django 5.1.3 on 2024-11-13 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes_en_Grupos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiantes_en_grupos',
            old_name='docente',
            new_name='id_docente',
        ),
        migrations.RenameField(
            model_name='estudiantes_en_grupos',
            old_name='estudiante',
            new_name='id_estudiante',
        ),
        migrations.RenameField(
            model_name='estudiantes_en_grupos',
            old_name='grupo',
            new_name='id_grupo',
        ),
        migrations.AlterUniqueTogether(
            name='estudiantes_en_grupos',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='estudiantes_en_grupos',
            table=None,
        ),
    ]
