# Generated by Django 5.1.3 on 2024-11-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('kinestesico', models.FloatField(blank=True, null=True)),
                ('visual', models.FloatField(blank=True, null=True)),
                ('auditivo', models.FloatField(blank=True, null=True)),
                ('estilo_predominante', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('contrasena', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'estudiantes',
            },
        ),
    ]
