# Generated by Django 5.1.3 on 2024-12-17 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes', '0002_alter_estudiante_table'),
        ('Grupos', '0002_alter_grupo_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='Grupos.grupo'),
        ),
    ]
