# Generated by Django 5.1.3 on 2024-11-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_grupo', models.CharField(max_length=100)),
                ('kinestesico', models.FloatField(blank=True, null=True)),
                ('auditivo', models.FloatField(blank=True, null=True)),
                ('visual', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'grupos',
            },
        ),
    ]
