# Generated by Django 5.1.3 on 2024-11-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_actividad', models.CharField(max_length=255)),
                ('estilo_kinestesico', models.CharField(blank=True, max_length=50, null=True)),
                ('estilo_auditivo', models.CharField(blank=True, max_length=50, null=True)),
                ('estilo_visual', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_actividad', models.CharField(max_length=50)),
                ('nivel_dificultad', models.CharField(max_length=50)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'actividades',
            },
        ),
    ]
