# Generated by Django 5.1.3 on 2024-11-13 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Actividades', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='actividad',
            table='Actividades',
        ),
    ]
