# Generated by Django 5.1.3 on 2024-11-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actividades', '0002_alter_actividad_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='estilo_auditivo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='estilo_kinestesico',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='estilo_visual',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
